### ISSUE TITLE
vtable.py: `'Namespace' object has no attribute 'original'`

### ISSUE THREAD

**Issue by disinvite** [isledecomp/reccmp#34]
A slight regression from #26. Output from isledecomp CI:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\hostedtoolcache\windows\Python\3.12.8\x64\Scripts\reccmp-vtable.exe\__main__.py", line 7, in <module>
  File "C:\hostedtoolcache\windows\Python\3.12.8\x64\Lib\site-packages\reccmp\tools\vtable.py", line 71, in main
    orig_bin = detect_image(args.original)
                            ^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'original'
```

It should get the orig and recomp binary filepaths from `target` not `args`.

**Comment by banjaminlee** [comment]
https://bold.pro/my/banjamin-lee-241212153841

This is my resume.
I want to work with you.
I look forward your reply.
